### ISSUE TITLE
Temperature units

### ISSUE THREAD

**Issue by spidgrou** [sbender9/signalk-shelly#15]
Hi,
First of all thanks a lot for your job, I love your work. 
I've just install the new UNI and I see in Signalk DataBrowser that the units of the temperature sent from the uni has shown in Kelvin.
Inside the UNI I select centigrade degree and also inside your config.
I don't understand if it is my issue or not.
Thanks for any help. 
![Screenshot_20210421-101153_Chrome](https://user-images.githubusercontent.com/42083306/115470733-dfde3380-a28a-11eb-8214-68ee926351da.jpg)
![Uploading Screenshot_20210421-101707_Chrome.jpg…]()

**Comment by sbender9** [comment]
Temperature in signalk is always Kelvin. So it looks good to me.

**Comment by sbender9** [comment]
We use SI units. It's up to the clients/displays to convert to the users preferred units.

**Comment by spidgrou** [comment]
Oh, ok! So I see K units but it is only a label that I have to manage, but the temperature has shown in decree Celsius as I configured in the UNI and your setup. Ok. No problem. Thanks Da: Scott Bender ***@***.***>Inviato: Mercoledì 21 Aprile 2021, 10:25A: sbender9/signalk-shellyCc: Max Terragni; AuthorOggetto: Re: [sbender9/signalk-shelly] Temperature units (#15)
We use SI units. It's up to the clients/displays to convert to the users preferred units.

**Comment by sbender9** [comment]
It should show as Kelvin in the Data Browser. If not, I made a mistake.

**Comment by spidgrou** [comment]
> It should show as Kelvin in the Data Browser. If not, I made a mistake.

In DataBrowser the value is Celsius
