### ISSUE TITLE
Support for the Shelly H&T?

### ISSUE THREAD

**Issue by kjenset** [sbender9/signalk-shelly#20]
Hi

Is it possible to get support for the Shelly H&T?

regards
Kristian

**Comment by kjenset** [comment]
Anyone?

**Comment by sbender9** [comment]
publish in v1.7.0 of the plugin

Please check the humidity value. I'm not sure what units that comes in from the device.

**Comment by mapeje** [comment]
I can confirm that the plugin reports both temperature and humidity. However, the temperature does not come in with any units ("K") like other temperature sensors.
