### ISSUE TITLE
Add support for Shelly Plus 1

### ISSUE THREAD

**Issue by keeskode** [sbender9/signalk-shelly#25]
Thanks a lot for your work so far on this. Can you add support for the Shelly Plus 1?

**Comment by sbender9** [comment]
I use this library: https://github.com/alexryd/node-shellies

It doesn't look like there is support there for it, unless there's another name?

**Comment by keeskode** [comment]
> I use this library: https://github.com/alexryd/node-shellies
> 
> It doesn't look like there is support there for it, unless there's another name?

Hmm, no it doesn't support. I've opened an issue there: https://github.com/alexryd/node-shellies/issues/33
