### ISSUE TITLE
Add support for Shelly Plus Plug US?

### ISSUE THREAD

**Issue by glover-glitch** [sbender9/signalk-shelly#35]
Would you be able to add support for the Shelly Plus Plug US please?
I have a few of these onboard monitoring power usage of various devices.

https://www.shelly.cloud/en-us/products/shop/shelly-plus-plug-us-1

**Comment by sbender9** [comment]
done, released in 1.13.0

**Comment by glover-glitch** [comment]
Perfect!

Thank you.
