### ISSUE TITLE
Shelly UNI temperature read out only at startup

### ISSUE THREAD

**Issue by Krillle** [sbender9/signalk-shelly#37]
The temperature values of my Shelly UNI are updated only once after startup. After no temperature changes any more.

Signal K Server version 1.45.0
signalk-shelly 1.13.0

I cant find any reason for that.

**Comment by sbender9** [comment]
Yep. They don't send out period updates. Only when it changes.

**Comment by Krillle** [comment]
The temperature didn't update all winter. The temperature readout changed from 10°C to 19,5° C after restart of Signal K.

**Comment by sbender9** [comment]
I don't know why it wouldn't update. And I don't have any Shelly devices with temperature to test with. You'd think someone else would have complained about this before...

**Comment by Krillle** [comment]
This I was indeed wondering as well. 
I am mapping the temperature with Path Mapper. Might this have side effects. 

How to log or crosscheck where the change of temperature is lost?

**Comment by sbender9** [comment]
I don't think path-mapper would have anything to do with it. 

Turn on debug for the plugin. You should messages when updates come in from the Shelly.

**Comment by Krillle** [comment]
Shelly UNI was not reporting temperature updates. 
Now it is working. False alarm.
