### ISSUE TITLE
SHHT-1 (Shelly H&T) to Kelvin conversion incorrect

### ISSUE THREAD

**Issue by tonybentley** [sbender9/signalk-shelly#45]
Given the SHHT-1 sensor has been discovered and the plugin is initialized

When the sensor temperature is set to either F or C in the web UI
The sensor always sends Celsius value
When the plugin evaluates the props?.tempUnits as `C`
Then conversion is correct
When the plugin does not evaluate the props?.tempUnits
The conversion is incorrect, as it assumes a F conversion

**Solution:**

Always convert from C to K and do not evaluate props?.tempUnits

**Workaround:**

`const convertCtoK = (val) => {
return val  + 273.15
}`

...

`
  'SHHT-1': {
      readPaths: [
        {
          key: 'temperature',
          converter: convertCtoK
        },
...
`

Tested on Shelly H&T sensor with latest firmware using Signalk server version 2.3 and plugin version 1.15.0

**Comment by sbender9** [comment]
This is why there is a setting in the plugin config. I can't tell how the device is configured.

**Comment by sbender9** [comment]
It does default to F, but you just need to change to C in the plugin config

**Comment by sbender9** [comment]
That may be specific to that device. I know there were some that you could change what it sends. 

But things work for you as long as you change the plugin config, right?

**Comment by tonybentley** [comment]
I had to make a code change for it to work. I will check and see if there is a way to do a sensor config change to avoid code changes. Once I verify, I will pull request on the README with more specific instructions.

**Comment by sbender9** [comment]
You changed the setting in the plugin config?

**Comment by tonybentley** [comment]
I reset the plugin to latest version and changed the plugin config between F and C, then also changed the F and C settings in the shelly sensor web UI. The bug is only when changing the plugin config to F. It seems to work if set to C, regardless of the sensor web UI settings. I think this issue is simply a need for documentation for proper configuration. Happy to help!

**Comment by sbender9** [comment]
Yep, I agree. A note in the README is probably enough. And need to make it clear that this does not effect next gen devices.

**Comment by tonybentley** [comment]
Closing since no code changes are required. Appreciate the support!
